### ISSUE TITLE
Incorrect directory name in kind_create.sh causing failed deployment

### ISSUE THREAD

**Issue by PatBStream** [datastax/pulsar_workshop#26]
https://github.com/datastax/pulsar_workshop/blob/775d4d8f7d0519f7ec3889c34b20fb9ed4366196/cluster_deploy/k8s/kind/kind_create.sh#L77

kindCfgFile="${WORKSHOP_HOMEDIR}/cluster_deploy/**kubernetes**/kind/cluster-config.yaml"  should be:
kindCfgFile="${WORKSHOP_HOMEDIR}/cluster_deploy/**k8s**/kind/cluster-config.yaml"

**Comment by PatBStream** [comment]
Also at:
https://github.com/datastax/pulsar_workshop/blob/775d4d8f7d0519f7ec3889c34b20fb9ed4366196/cluster_deploy/k8s/kind/kind_create.sh#L83

**Comment by yabinmeng** [comment]
Fixed
