### ISSUE TITLE
$WORKSHOP_HOMEDIR not defined, should be $PULAR_WORKSHOP_HOME, in kind_create.sh

### ISSUE THREAD

**Issue by PatBStream** [datastax/pulsar_workshop#28]
https://github.com/datastax/pulsar_workshop/blob/775d4d8f7d0519f7ec3889c34b20fb9ed4366196/cluster_deploy/k8s/kind/kind_create.sh#L77

https://github.com/datastax/pulsar_workshop/blob/775d4d8f7d0519f7ec3889c34b20fb9ed4366196/cluster_deploy/k8s/kind/kind_create.sh#L83

**Comment by yabinmeng** [comment]
Fixed
