### ISSUE TITLE
Invalid --connFile parameter created in run_nativeapi scripts, when deployed with scenario.infra_mode=luna_existing

### ISSUE THREAD

**Issue by PatBStream** [datastax/pulsar_workshop#29]
Both producer and consumer run scripts have invalid --connFile parameters.  
`java \
  -cp /home/pat/newproject/pulsar_workshop/scenarios/demo-scenario-1/appexec/package/nativeapi_consumer_full_config.jar \
  com.example.pulsarworkshop.PulsarConsumerFullCfg \
  -numMsg 10 -topic public/default/t1 -**connFile /Users/yabinmeng/MyFolder/Yabin.Work/PSA.Vanguard/**pulsar_workshop/scenarios/demo-scenario-1/client.conf -sbn mysub
`
To re-create, run script from ~/pulsar_workshop/scenarios
`./deployScenario.sh -scnName demo-scenario-1`

**Comment by yabinmeng** [comment]
Please paste the error message you've seen.
