### ISSUE TITLE
Minor issue, NativeAPI Consumer options state "Number of messages to produce"  Should be "consume"

### ISSUE THREAD

**Issue by PatBStream** [datastax/pulsar_workshop#30]
https://github.com/datastax/pulsar_workshop/blob/775d4d8f7d0519f7ec3889c34b20fb9ed4366196/application_code/client_apps/java/nativeapi_consumer_full_config/src/main/java/com/example/pulsarworkshop/PulsarConsumerFullCfg.java#L31

Help context should also state "-1" for continuous run.

`$ java -cp nativeapi_consumer_full_config-1.0.0.jar com.example.pulsarworkshop.PulsarConsumerFullCfg -h
usage: appNme [-as] [-cfg <arg>] [-con <arg>] [-h] [-num <arg>] [-sbn <arg>] [-sbt <arg>] [-top <arg>]
Command Line Options:
  -as,--astra           Whether to use Astra streaming.
  -cfg,--cfgFile <arg>  Extra config properties file path.
  -con,--connFile <arg> "client.conf" file path.
  -h,--help             Displays the usage method.
  -num,--numMsg <arg>   Number of message to **produce**.
  -sbn,--subName <arg>  Pulsar subscription name.
  -sbt,--subType <arg>  Pulsar subscription type.
  -top,--topic <arg>    Pulsar topic name.`

**Comment by yabinmeng** [comment]
Fixed
